remote_theme: antonostrovsky/tale
twitter_username: "aaa"
formspree_id: "aaa"
github_repo: "aaa"
base_url: "/test_site"

title: Test website

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
